### ISSUE TITLE
Cannot delete a host

### ISSUE THREAD

**Issue by simoncrook** [TAKEALOT/nodervisor#20]
Hi there,

When I try to delete a host by clicking on the delete button takes me back to the main hosts page but the host is still there and not deleted. n the console output I get:

GET /js/jquery-1.10.1.min.js 304 49ms
GET /js/bootstrap.min.js 304 51ms
GET /js/vendor/modernizr-2.6.2-respond-1.1.0.min.js 304 55ms
GET /js/vendor/ejs_production.js 304 41ms
GET /js/vendor/moment.min.js 304 35ms
Knex: The five argument join syntax is now deprecated, please check the docs and update your code.
POST /host/1 302 5ms - 68b
Knex: The five argument join syntax is now deprecated, please check the docs and update your code.
GET /hosts 200 11ms - 3.89kb
GET /css/bootstrap.min.css 304 13ms
GET /css/bootstrap-responsive.min.css 304 20ms
GET /css/normalize.min.css 304 23ms
GET /css/main.css 304 26ms
GET /css/font-awesome.min.css 304 29ms
GET /js/jquery-1.10.1.min.js 304 33ms
GET /js/bootstrap.min.js 304 37ms
GET /js/vendor/modernizr-2.6.2-respond-1.1.0.min.js 304 41ms
GET /js/vendor/ejs_production.js 304 34ms
GET /js/vendor/moment.min.js 304 31ms

Is this anything to do with "Knex: The five argument join syntax is now deprecated, please check the docs and update your code" line ???

Thanks,
Simon

**Comment by Krylik** [comment]
I have just merged #27 , which fixes this bug. I changed the schema at some point and that one slipped through :) Thanks @rk295 .
