### ISSUE TITLE
Grouped process is visible in UI but cannot be started and stopped

### ISSUE THREAD

**Issue by chrisbeach** [TAKEALOT/nodervisor#22]
A process can be a member of a group in Supervisor. 

When running the status command within supervisorctl, the process is represented as [groupName]:[processName]

In the Nodervisor UI, the process is represented just as [processName] and it seems it can't be started and stopped (nothing happens when clicking the button)

**Comment by Krylik** [comment]
I believe this has been fixed with the merge of #23 . Thanks @klacointe .
